### ISSUE TITLE
Using under Synology Docker

### ISSUE THREAD

**Issue by TheBassfly** [mariomare22/docker-pihole-unbound#13]
Hey

Is there a manual how to install this fork under Synology Docker? Because the usual way doesn't find the image of this package.

**Comment by pluim003** [comment]
I tried through:

```
pi@raspberrypi4:~/pi-hole $ docker pull ghcr.io/mariomare22/docker-pihole-unbound:latest
latest: Pulling from mariomare22/docker-pihole-unbound
5731adb3a4ab: Already exists
df40c53e6b66: Already exists
4f4fb700ef54: Already exists
2dff53955dde: Already exists
34575e9e3344: Already exists
44048c8f578a: Already exists
5112faa29188: Already exists
79368a84c86e: Already exists
a73f1490e597: Already exists
a73880171762: Pull complete
fd8dd0ed9c09: Pull complete
816b090e6610: Pull complete
1e1c0c38c16b: Pull complete
7a9e3d9782db: Pull complete
2335280ee43c: Pull complete
7aa3e52463a2: Pull complete
Digest: sha256:83e7da2896fb622b3814ea71b0e4f0c912de10b214d4efb6cd527cb133c96f3d
Status: Downloaded newer image for ghcr.io/mariomare22/docker-pihole-unbound:latest
ghcr.io/mariomare22/docker-pihole-unbound:latest
```

Guess it shouldn't be different on a Synology with respect to a RPi. Could you try this?

**Comment by TheBassfly** [comment]
Unfortunately not.
I can only install Packages, that are offered by the Sinology Docker itself.

For Example from MarioMare22, I can only install the docker-samba-timemachine.

**Comment by pluim003** [comment]
Ok, no, then I don't have a clue.

**Comment by TheBassfly** [comment]
Thank you for your input.
I'm not so much into this theme to save it by myself. Maybe I switch back to the official pihole without the unbound.

**Comment by mariomare22** [comment]
I guess it is because docker samba was packaged for hub.docker.com.
I am trying to detach from it and use only ghcr.io
