### ISSUE TITLE
DoT not working as expected

### ISSUE THREAD

**Issue by mariomare22** [mariomare22/docker-pihole-unbound#8]
DoT not getting enabled

**Comment by mariomare22** [comment]
@keanugithub Can you please post your docker-compose.yml file?

**Comment by keanugithub** [comment]
![image](https://user-images.githubusercontent.com/98110531/217827652-25226513-b98d-4692-9fbd-b6a9f52be78e.png)

sure here it is,

`version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: homeserver
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.1.11
      - TZ=Asia/Manila
      - WEBPASSWORD=
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_CIDR=192.168.0.0/16
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
`

**Comment by mariomare22** [comment]
yeah as suspected you are still using the old compose (my bad i did not edit it with new image), I focused on the `Dockerfile`

check the updated one [docker-compose.yml](https://github.com/mariomare22/docker-pihole-unbound/blob/main/docker-compose.yaml ) which I just committed. 
before deploying clean up folders and volumes.
let me know

**Comment by mariomare22** [comment]
Reopen if help needed

**Comment by keanugithub** [comment]
seems like i have a problem with the pihole version here unlike on the original. plus the volumes idk pls help thank you
![image](https://user-images.githubusercontent.com/98110531/217840930-60ea777b-8a4b-49de-a78a-4ce84f010fa9.png)

**Comment by keanugithub** [comment]
what should i put in pwd? the directory where i cloned ur fork right?? btw, i cant reopen an issue, seems like only the creator.

**Comment by mariomare22** [comment]
there is no need to clone the whole repo, just the docker-compose file.
I am trying to build the image for arm7 but I am still new to CI/CD, so feel free if you cloned the repo to try and build the image by yourself `docker build .`

**Comment by keanugithub** [comment]
the original repo works for me, i just want to try the DoT feature..

**Comment by mariomare22** [comment]
https://github.com/mariomare22/docker-pihole-unbound/issues/9#issuecomment-1424353339

**Comment by keanugithub** [comment]
thanks, how about the volume, what will i put in pwd??

**Comment by keanugithub** [comment]
gives off this error when i put my home directory.. 
![image](https://user-images.githubusercontent.com/98110531/217858035-bc9fee2d-3e06-4e74-9e18-2977e4183fb5.png)

**Comment by keanugithub** [comment]
i added this one at the top;
![image](https://user-images.githubusercontent.com/98110531/217877778-a73e6091-0b3d-4f11-a0ae-e543b53c06c3.png)

then simply this:
![image](https://user-images.githubusercontent.com/98110531/217877850-5979134d-403a-4444-9251-8802519e8699.png)


and now it works thank you very much!!
![image](https://user-images.githubusercontent.com/98110531/217877983-add118f2-4e43-47d5-90b6-1be88beb5bce.png)
